### PR TITLE
Fix race condition so only one worker may poll a given job

### LINKED ISSUE #98: Race condition: 2 workers poll the same job
API:
2018-01-26 20:49:36,196 [http-server-16] INFO  org.dataportabilityproject.job.PortabilityJobFactory - Creating new PortabilityJob, id: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e

Worker 1:

2018-01-26 20:50:12,244 [JobPollingService RUNNING] DEBUG org.dataportabilityproject.worker.JobPollingService - Polled pollForUnassignedJob, found id: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e
2018-01-26 20:50:12,943 [JobPollingService RUNNING] DEBUG org.dataportabilityproject.worker.JobPollingService - Completed updateJobStateToAssignedWithoutAuthData, publicKey: 162

2018-01-26 20:50:33,051 [JobPollingService RUNNING] DEBUG org.dataportabilityproject.worker.JobPollingService - Polled lookupAssignedWithAuthDataJob, found auth data, id: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e
2018-01-26 20:50:33,056 [main] DEBUG org.dataportabilityproject.worker.WorkerImpl - Begin processing jobId: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e
Jan 26, 2018 8:50:33 PM com.google.common.util.concurrent.UncaughtExceptionHandlers$Exiter uncaughtException
SEVERE: Caught an exception in Thread[main,5,main].  Shutting down.
java.lang.RuntimeException: Failed to invoke public org.dataportabilityproject.shared.auth.AuthData() with no args
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:107)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at org.dataportabilityproject.worker.WorkerImpl.deSerialize(WorkerImpl.java:108)
	at org.dataportabilityproject.worker.WorkerImpl.processJob(WorkerImpl.java:92)
	at org.dataportabilityproject.worker.WorkerImpl.processJob(WorkerImpl.java:69)
	at org.dataportabilityproject.worker.WorkerMain.main(WorkerMain.java:31)
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:104)

Worker 2:

2018-01-26 20:50:12,382 [JobPollingService RUNNING] DEBUG org.dataportabilityproject.worker.JobPollingService - Polled pollForUnassignedJob, found id: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e
Jan 26, 2018 8:50:12 PM com.google.common.util.concurrent.UncaughtExceptionHandlers$Exiter uncaughtException
SEVERE: Caught an exception in Thread[main,5,main].  Shutting down.
java.lang.IllegalStateException: Expected the service JobPollingService [FAILED] to be TERMINATED, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
	at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:293)
	at com.google.common.util.concurrent.AbstractScheduledService.awaitTerminated(AbstractScheduledService.java:434)
	at org.dataportabilityproject.worker.WorkerImpl.pollForJob(WorkerImpl.java:75)
	at org.dataportabilityproject.worker.WorkerImpl.processJob(WorkerImpl.java:60)
	at org.dataportabilityproject.worker.WorkerMain.main(WorkerMain.java:31)
Caused by: java.lang.IllegalArgumentException: Job not found
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.dataportabilityproject.job.JobDao.updateJobState(JobDao.java:224)
	at org.dataportabilityproject.job.JobDao.updateJobStateToAssignedWithoutAuthData(JobDao.java:173)
	at org.dataportabilityproject.worker.JobPollingService.pollForUnassignedJob(JobPollingService.java:83)
	at org.dataportabilityproject.worker.JobPollingService.runOneIteration(JobPollingService.java:57)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:188)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by rtannenbaum**
Fixes #98 

Use a database transaction for updating job state

Make worker gracefully handle the condition when another worker has claimed the job it tried to poll

Tested in QA. Worker 1 claims the job and starts processing it, worker 2 tries and fails to claim the job, and resumes polling for a new job

### CODE REVIEW

**Comment by rtannenbaum** [comment]
I messed up the rebasing of this one too since I tried to squash commits that had already been pushed to remote. Next time...

File: portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java [hunk 1]
```diff
@@ -46,12 +46,97 @@
 
   private final Datastore datastore;
 
+  // Current transaction for completing atomic operations. Only one atomic transaction may be
+  // executed at a time. Null if we are not currently completing a transaction.
+  private Transaction currentTransaction = null;
```
Comment (holachuy) [inline portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java]: I think there is a potential for java concurrency issues.  Multiple threads could make calls to an instance of this class and receive different state.

One solution we could try is to to expose a simple interface for atomic updates that will implement the underlying datastores transactions:
https://cloud.google.com/datastore/docs/concepts/transactions#datastore-transactional-update-java

There may be others.

Comment (rtannenbaum) [reply portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java]: Yeah, was wondering about concurrency issues. In the API, right?

What do you think about instead of the current transaction, I use a concurrent map of id -> transaction, and let the users of this class pass the transaction ID?

**Comment by rtannenbaum** [comment]
@holachuy PTAL? I made this use an atomic update method that hides transaction impl details, I think it's much cleaner now so thanks for the suggestion.

**Comment by rtannenbaum** [comment]
also tested again in QA and it still works

File: portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java [hunk 2]
```diff
@@ -52,8 +57,69 @@ public GooglePersistentKeyValueStore(Datastore datastore) {
...
+  @Override
+  public boolean atomicUpdate(String previousKeyStr, String newKeyStr, Map<String, Object> data) {
+    Transaction transaction = datastore.newTransaction();
+
+    try {
+      Key previousKey = getKey(previousKeyStr);
+      Entity previousEntity = transaction.get(previousKey);
+      if (previousEntity == null) {
+        logger.debug("Could not find previous key {}", previousKeyStr);
+        return false;
```
Comment (holachuy) [inline portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java]: Do we have to do anything with the transaction here?

File: portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java [hunk 3]
```diff
@@ -52,8 +57,69 @@ public GooglePersistentKeyValueStore(Datastore datastore) {
...
+      }
+
+      Key newKey = getKey(newKeyStr);
+      Entity newEntity = transaction.get(newKey);
+      if (newEntity != null) {
+        logger.debug("Updated key already exists: {}", newKeyStr);
```
Comment (holachuy) [inline portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java]: Do we have to do anything with the transaction here?

File: portability-worker/src/main/java/org/dataportabilityproject/worker/JobPollingService.java [hunk 4]
```diff
@@ -71,17 +71,20 @@ private void pollForUnassignedJob() throws IOException {
...
       // Executing Job State Transition from Unassigned to Assigned
-      jobDao.updateJobStateToAssignedWithoutAuthData(id, publicKey, privateKey);
-      logger.debug("Completed updateJobStateToAssignedWithoutAuthData, publicKey: {}", publicKey.getEncoded().length);
+      if (jobDao.updateJobStateToAssignedWithoutAuthData(id, publicKey, privateKey)) {
+        logger.debug("Completed updateJobStateToAssignedWithoutAuthData, publicKey: {}",
+            publicKey.getEncoded().length);
+      } else {
+        logger.debug("Failed to claim job {}; it was probably already claimed by another worker",
+            id);
+        jobMetadata.reset();
```
Comment (holachuy) [inline portability-worker/src/main/java/org/dataportabilityproject/worker/JobPollingService.java]: Instead of reset. Let's create the public and private key outside of the jobMetatData.

Then we update the method call jobMetadata.init(id, publicKey, privateKey) if we're successful in assigning the.

Another option is to process the assignment update then, when that succeeds, update with the key info.

Thoughts?

File: portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java (hunk 2 above)
Comment (rtannenbaum) [reply portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java]: Good catch, rolled it back

File: portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java (hunk 3 above)
Comment (rtannenbaum) [reply portability-core/src/main/java/org/dataportabilityproject/cloud/google/GooglePersistentKeyValueStore.java]: same here

File: portability-worker/src/main/java/org/dataportabilityproject/worker/JobPollingService.java (hunk 4 above)
Comment (rtannenbaum) [reply portability-worker/src/main/java/org/dataportabilityproject/worker/JobPollingService.java]: Good idea, done
